### ISSUE TITLE
required_ruby_version is incorrect

### ISSUE THREAD

**Issue by jeremyevans** [rails/execjs#129] opened 2023-09-14 18:28 UTC
The 2.9.0 gem advertises Ruby 1.9.3 support, but it requires Ruby 2.3.  This broke tilt's CI on Ruby 2.0 and 2.1.

```
/home/runner/work/tilt/tilt/vendor/bundle/ruby/2.1.0/gems/execjs-2.9.0/lib/execjs/runtimes.rb:4:in `require': /home/runner/work/tilt/tilt/vendor/bundle/ruby/2.1.0/gems/execjs-2.9.0/lib/execjs/external_runtime.rb:106: syntax error, unexpected ',', expecting keyword_end (SyntaxError)
        instance_eval <<~RUBY, __FILE__, __LINE__
```

`required_ruby_version` in the gemspec should be updated to `>= 2.3`.

**Comment by byroot** [comment] 2023-09-15 06:25
Duplicate of https://github.com/rails/execjs/issues/128.

It's fixed on master.

**Closed by byroot** 2023-09-15 06:25 UTC
