### ISSUE TITLE
Rails 4.2 + v2.8.1 == TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by baburdick** [rails/execjs#102] opened 2021-05-15 00:46 UTC
Running specs in my Rails 4.2 application after upgrading to v2.8.1 produces this failure:
```
eval (eval at <anonymous> ((execjs):1:275), <anonymous>:1:10)
(execjs):1:275
(execjs):19:14
(execjs):1:102
Object.<anonymous> ((execjs):1:120)
Module._compile (internal/modules/cjs/loader.js:689:30)
Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Module.load (internal/modules/cjs/loader.js:599:32)
tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Function.Module._load (internal/modules/cjs/loader.js:530:3)
~/.rvm/gems/ruby-2.6.6@my_app/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:39:in `exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/execjs-2.8.1/lib/execjs/external_runtime.rb:21:in `eval'
~/.rvm/gems/ruby-2.6.6@my_app/gems/execjs-2.8.1/lib/execjs/runtime.rb:64:in `eval'
~/.rvm/gems/ruby-2.6.6@my_app/gems/autoprefixer-rails-9.6.1/lib/autoprefixer-rails/processor.rb:153:in `runtime'
~/.rvm/gems/ruby-2.6.6@my_app/gems/autoprefixer-rails-9.6.1/lib/autoprefixer-rails/processor.rb:36:in `process'
~/.rvm/gems/ruby-2.6.6@my_app/gems/autoprefixer-rails-9.6.1/lib/autoprefixer-rails/sprockets.rb:20:in `run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/autoprefixer-rails-9.6.1/lib/autoprefixer-rails/sprockets.rb:14:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:50:in `each'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:50:in `map'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:50:in `precompiled_assets'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:35:in `asset_precompiled?'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:252:in `block (3 levels) in <class:Railtie>'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:368:in `precompiled?'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:372:in `raise_unless_precompiled_asset'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:338:in `digest_path'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:326:in `asset_path'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:103:in `block in resolve_asset_path'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `each'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `detect'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:242:in `resolve_asset'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:102:in `resolve_asset_path'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:80:in `compute_asset_path'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/helpers/asset_url_helper.rb:245:in `javascript_path'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/helpers/asset_tag_helper.rb:61:in `block in javascript_include_tag'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/helpers/asset_tag_helper.rb:59:in `map'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/helpers/asset_tag_helper.rb:59:in `javascript_include_tag'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:157:in `block in javascript_include_tag'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:155:in `map'
~/.rvm/gems/ruby-2.6.6@my_app/gems/sprockets-rails-3.2.2/lib/sprockets/rails/helper.rb:155:in `javascript_include_tag'
./app/views/widgets_select/show.html.haml:2:in `block in _app_views_widgets_select_show_html_haml___812906312290663528_70134070184820'
~/.rvm/gems/ruby-2.6.6@my_app/gems/haml-5.2.1/lib/haml/helpers.rb:379:in `block in capture_haml'
~/.rvm/gems/ruby-2.6.6@my_app/gems/haml-5.2.1/lib/haml/helpers.rb:670:in `with_haml_buffer'
~/.rvm/gems/ruby-2.6.6@my_app/gems/haml-5.2.1/lib/haml/helpers.rb:375:in `capture_haml'
~/.rvm/gems/ruby-2.6.6@my_app/gems/haml-5.2.1/lib/haml/helpers/xss_mods.rb:66:in `capture_haml_with_haml_xss'
~/.rvm/gems/ruby-2.6.6@my_app/gems/haml-5.2.1/lib/haml/helpers/action_view_mods.rb:46:in `capture_with_haml'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/helpers/capture_helper.rb:152:in `content_for'
./app/views/widgets_select/show.html.haml:1:in `_app_views_widgets_select_show_html_haml___812906312290663528_70134070184820'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/template.rb:145:in `block in render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `block in instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/web_events-0.7.0/lib/web_events.rb:41:in `instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/template.rb:337:in `instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/template.rb:143:in `render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `block in instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/web_events-0.7.0/lib/web_events.rb:41:in `instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/template_renderer.rb:14:in `render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/renderer.rb:46:in `render_template'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/renderer/renderer.rb:27:in `render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/rendering.rb:100:in `_render_template'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/streaming.rb:217:in `_render_template'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/rendering.rb:83:in `render_to_body'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/abstract_controller/rendering.rb:25:in `render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/rendering.rb:16:in `render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
~/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/core_ext/benchmark.rb:12:in `ms'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activerecord-4.2.11.3/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/abstract_controller/base.rb:198:in `process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:117:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:505:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/callbacks.rb:81:in `run_callbacks'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/web_events-0.7.0/lib/web_events.rb:72:in `block in process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `block in instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/web_events-0.7.0/lib/web_events.rb:41:in `instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activesupport-4.2.11.3/lib/active_support/notifications.rb:164:in `instrument'
~/.rvm/gems/ruby-2.6.6@my_app/gems/web_events-0.7.0/lib/web_events.rb:69:in `process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/activerecord-4.2.11.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/abstract_controller/base.rb:137:in `process'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionview-4.2.11.3/lib/action_view/rendering.rb:30:in `process'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/test_case.rb:639:in `process'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/test_case.rb:67:in `process'
~/.rvm/gems/ruby-2.6.6@my_app/gems/devise-4.6.2/lib/devise/test/controller_helpers.rb:35:in `block in process'
~/.rvm/gems/ruby-2.6.6@my_app/gems/devise-4.6.2/lib/devise/test/controller_helpers.rb:102:in `catch'
~/.rvm/gems/ruby-2.6.6@my_app/gems/devise-4.6.2/lib/devise/test/controller_helpers.rb:102:in `_catch_warden'
~/.rvm/gems/ruby-2.6.6@my_app/gems/devise-4.6.2/lib/devise/test/controller_helpers.rb:35:in `process'
~/.rvm/gems/ruby-2.6.6@my_app/gems/actionpack-4.2.11.3/lib/action_controller/test_case.rb:514:in `get'
./spec/controllers/widgets_select_controller_spec.rb:65:in `block (4 levels) in <top (required)>'
~/.rvm/gems/ruby-2.6.6@my_app/gems/vcr-6.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
~/.rvm/gems/ruby-2.6.6@my_app/gems/vcr-6.0.0/lib/vcr.rb:194:in `use_cassette'
./spec/controllers/widgets_select_controller_spec.rb:44:in `block (3 levels) in <top (required)>'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-rails-4.1.2/lib/rspec/rails/example/controller_example_group.rb:191:in `block (2 levels) in <module:ControllerExampleGroup>'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-rails-4.1.2/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:124:in `block in run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `loop'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:110:in `run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-retry-0.6.2/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-retry-0.6.2/lib/rspec/retry.rb:37:in `block (2 levels) in setup'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
~/.rvm/gems/ruby-2.6.6@my_app/gems/rspec-core-3.10.1/exe/rspec:4:in `<main>'
------------------
--- Caused by: ---
ExecJS::ProgramError:
  TypeError: Cannot read property 'version' of undefined
  eval (eval at <anonymous> ((execjs):1:275), <anonymous>:1:10)
```
Reverting to v2.7.0 fixes the issue.

**Comment by byroot** [comment] 2021-05-15 06:54
Duplicate of https://github.com/rails/execjs/issues/99 and https://github.com/ai/autoprefixer-rails/issues/203

**Closed by byroot** 2021-05-15 06:54 UTC
